### ISSUE TITLE
On Linux, 'sudo apt install cmake ninja-build' calls cmake v. 3.10.2 but M4 sample required v. 3.11.

### ISSUE THREAD

**Issue by Shieroo** [CodethinkLabs/mt3620-m4-samples#8]
On Linux, when type the <sudo install cmake ninja-build> command, I'm getting cmake version 3.10.2. 

However, the all M4 RTapps require Cmake minimum version 3.11.
The end users notice the failure after build and run the app then need to set it up again. Can you explain the steps for setting a higher version manually, or make it compatible with a lower version, to save time for the end user and for a better user experience? Thanks.

**Comment by aiden-ct** [comment]
Hi @Shieroo - we haven't tested compilation of our samples on linux (sounds like you're running Ubuntu 18.04) yet. But you should be able to just build and install cmake from source. This answer on stack overflow goes over the steps: https://askubuntu.com/a/865294/387450, but you should be able to just download the source from https://cmake.org/download/. In order to make a plug and play environment to improve the usability of our samples, we might need to make a Dockerfile with all of the build dependencies at the right versions. If you have experience with Docker, please feel free contributing a Dockerfile to the samples repo.
